# <center>PyTen Package Tutorial</center>
#### <center>Texas A&M University HELIOS Group</center>

## Import PyTen Packge

In [1]:
import pyten

## Quick Start

In [2]:
# This is a quick start without prior input
[OriTensor, DeTensor, TenClass, RecTensor] = pyten.UI.helios()

Please choose the Scenario:
 1. Basic Tensor Decomposition/Completion  2.Tensor Completion with Auxiliary Information 3.Dynamic Tensor Decomposition 0.Exit 
1
Please input the FileName of the data:
syntensor.csv


Please choose the method you want to use to recover data(Input one number):
 1. Tucker(ALS)  2.CP(ALS) 3.NNCP(Trace Norm + ADMM, Only For Recovery) 4.SiLRTC(Only For Recovery) 5.FaLRTC(Only For Recovery) 6.HaLRTC(Only For Recovery)  0.Exit 
1


If there are missing values in the file? (Input one number)
1. Yes, recover it  2.No, just decompose(Nonexistent number will be replaced by 0) 0.Exit
1

The original Tensor is: 
[[[    nan     nan     nan     nan]
  [ 0.0193     nan  0.023   0.0138]]

 [[    nan  0.0209     nan  0.0192]
  [ 0.2244  0.4468  0.4514  0.2389]]

 [[    nan  0.4337  0.3854     nan]
  [ 0.0098  0.0198  0.0199  0.0105]]]

The Recovered Tensor is: 
[[[  5.36419601e-03   1.15819293e-02   2.41556847e-02   5.87467447e-03]
  [  1.93000000e-02   3.13164514e-02   2.3

Show Results as follows:
* Original Tensor

In [4]:
print OriTensor  # Original Tensor

[[[    nan     nan     nan     nan]
  [ 0.0193     nan  0.023   0.0138]]

 [[    nan  0.0209     nan  0.0192]
  [ 0.2244  0.4468  0.4514  0.2389]]

 [[    nan  0.4337  0.3854     nan]
  [ 0.0098  0.0198  0.0199  0.0105]]]


* Full Tensor reconstructed by decomposed matrices

In [5]:
print DeTensor.data  # Full Tensor reconstructed by decomposed matrices

[[[  5.36419601e-03   1.15819293e-02   2.41556847e-02   5.87467447e-03]
  [  1.60617081e-02   3.13164514e-02   2.29674417e-02   1.69441312e-02]]

 [[ -2.70223757e-03   1.09601902e-01   1.68232255e+00   1.92195701e-02]
  [  2.16621456e-01   4.30914180e-01   4.35331809e-01   2.30166163e-01]]

 [[ -5.85222615e-04   2.37113771e-02   3.63972026e-01   4.15755916e-03]
  [  4.68648339e-02   9.32259289e-02   9.41826071e-02   4.97951684e-02]]]


* Final Decomposition Results e.g. Ttensor or Ktensor

In [6]:
print TenClass  # Final Decomposition Results e.g. Ttensor or Ktensor

Ttensor of size (3, 2, 4)
Core = Tensor of size (2, 2, 2) with 8 elements.
 
u[0] =
[[-0.02147233 -0.99976944]
 [-0.97716179  0.02096416]
 [-0.21140903  0.00464502]]
u[1] =
[[ 0.95745405 -0.28858577]
 [ 0.28858577  0.95745405]]
u[2] =
[[ 0.03428678 -0.42558577]
 [ 0.13092771 -0.77884123]
 [ 0.98961198  0.13930304]
 [ 0.04848165 -0.4391785 ]]



* Recovered Tensor (Completed Tensor)

In [7]:
print RecTensor.data  # Recovered Tensor (Completed Tensor)

[[[  5.36419601e-03   1.15819293e-02   2.41556847e-02   5.87467447e-03]
  [  1.93000000e-02   3.13164514e-02   2.30000000e-02   1.38000000e-02]]

 [[ -2.70223757e-03   2.09000000e-02   1.68232255e+00   1.92000000e-02]
  [  2.24400000e-01   4.46800000e-01   4.51400000e-01   2.38900000e-01]]

 [[ -5.85222615e-04   4.33700000e-01   3.85400000e-01   4.15755916e-03]
  [  9.80000000e-03   1.98000000e-02   1.99000000e-02   1.05000000e-02]]]


## Three UI Functions For Three Scenarios
### Scenario 1: Basic Tensor completion or decomposition.

In [8]:
[OriTensor, DeTensor, TenClass, RecTensor] = pyten.UI.basic()

Please input the FileName of the data:
syntensor.csv


Please choose the method you want to use to recover data(Input one number):
 1. Tucker(ALS)  2.CP(ALS) 3.NNCP(Trace Norm + ADMM, Only For Recovery) 4.SiLRTC(Only For Recovery) 5.FaLRTC(Only For Recovery) 6.HaLRTC(Only For Recovery)  0.Exit 
2


If there are missing values in the file? (Input one number)
1. Yes, recover it  2.No, just decompose(Nonexistent number will be replaced by 0) 0.Exit
1

The original Tensor is: 
[[[    nan     nan     nan     nan]
  [ 0.0193     nan  0.023   0.0138]]

 [[    nan  0.0209     nan  0.0192]
  [ 0.2244  0.4468  0.4514  0.2389]]

 [[    nan  0.4337  0.3854     nan]
  [ 0.0098  0.0198  0.0199  0.0105]]]

The Recovered Tensor is: 
[[[-0.00173744 -0.00422459 -0.00260547 -0.00171897]
  [ 0.0193      0.02665745  0.023       0.0138    ]]

 [[ 0.01522447  0.0209      0.04088197  0.0192    ]
  [ 0.2244      0.4468      0.4514      0.2389    ]]

 [[ 0.20577687  0.4337      0.3854      0.2163867 ]
  [ 0.009

### Scenario 2: Tensor completion or decomposition with auxiliary information

In [11]:
[OriTensor, DeTensor, TenClass, RecTensor] = pyten.UI.auxiliary()

Please input the FileName of the Tensor data:
syntensor.csv


Please choose the method you want to use to recover data(Input one number):
 1. AirCP  2.CMTF 0.Exit 
1


Please input all the modes that have Auxiliary Similarity Matrix (separate with space. Input 'None' if no auxiliary info.)
None
If there are missing values in the file? (Input one number)
1. Yes, recover it  2.No, just decompose(Nonexistent number will be replaced by 0) 0.Exit
1
AirCP: iterations=4, difference=4.25458316215e-14

The original Tensor is: 
[[[    nan     nan     nan     nan]
  [ 0.0193     nan  0.023   0.0138]]

 [[    nan  0.0209     nan  0.0192]
  [ 0.2244  0.4468  0.4514  0.2389]]

 [[    nan  0.4337  0.3854     nan]
  [ 0.0098  0.0198  0.0199  0.0105]]]

The Recovered Tensor is: 
[[[  2.11431057e-20   4.20984494e-20   4.04741882e-20   2.45562224e-20]
  [  1.93000000e-02   9.33334313e-20   2.30000000e-02   1.38000000e-02]]

 [[  2.39923722e-19   2.09000000e-02   4.63533286e-19   1.92000000e-02]
  [  2.24

### Scenario 3: Dynamic/Online/Streaming Tensor completion or decomposition

In [12]:
[OriTensor, DeTensor, TenClass, RecTensor] = pyten.UI.dynamic()

Please input the FileName of the data:
syntensor.csv


Please choose the method you want to use (Input one number):
 1. onlineCP(only for decomposition)  2.OLSGD 0.Exit 
1


If there are former decomposition or recovery result (.npy file):
 1. Yes  2.No 0.Exit 
2

CP_ALS:

CP_ALS: iterations=42, f=0.968019474699, f-delta=8.26504065188e-09

The original Tensor is: 
[[[    nan     nan     nan     nan]
  [ 0.0193     nan  0.023   0.0138]]

 [[    nan  0.0209     nan  0.0192]
  [ 0.2244  0.4468  0.4514  0.2389]]

 [[    nan  0.4337  0.3854     nan]
  [ 0.0098  0.0198  0.0199  0.0105]]]

The Decomposed Result is: 
[array([[ -8.09995873e-04,   2.87410936e-02],
       [ -7.58855491e-03,   8.15157310e-01],
       [  5.66073869e-01,   3.55594569e-02]]), array([[  1.00000000e+00,   3.24680048e-02],
       [  6.68461565e-04,   8.80131434e-01]]), array([[ -4.41267378e-04,   3.12909475e-01],
       [  7.64642525e-01,   6.22524427e-01],
       [  6.79819173e-01,   6.28936381e-01],
       [ -9.252397

## Usage of Main Functions
### Function: create
1. Create Tensor Completion Problem

In [13]:
from pyten.tools import create  # Import the problem creation function

problem = 'basic'  # Problem Definition
siz = [20, 20, 20]  # Size of the Created Synthetic Tensor
r = [4, 4, 4]  # Rank of the Created Synthetic Tensor
miss = 0.8  # Missing Percentage
tp = 'CP'  # Solution Format (Creating Method) of the Created Synthetic Tensor
[X1, Omega1, sol1] = create(problem, siz, r, miss, tp)

### Scenario 1: Basic Tensor Completion/Decomposition
#### 1. Solve Synthetic Completion Problem

In [14]:
from pyten.tools import create  # Import the problem creation function

problem = 'basic'  # Define Problem As Basic Tensor Completion Problem
siz = [20, 20, 20]  # Size of the Created Synthetic Tensor
r = [4, 4, 4]  # Rank of the Created Synthetic Tensor
miss = 0.8  # Missing Percentage
tp = 'CP'  # Define Solution Format of the Created Synthetic Tensor As 'CP decomposition'
[X1, Omega1, sol1] = create(problem, siz, r, miss, tp)

# Basic Tensor Completion with methods: CP-ALS,Tucker-ALS, FaLRTC, SiLRTC, HaLRTC, TNCP
from pyten.method import *

r = 4  # Rank for CP-based methods
R = [4, 4, 4]  # Rank for tucker-based methods
# P-ALS
[T1, rX1] = cp_als(X1, r, Omega1)  # if no missing data just omit Omega1 by using [T1,rX1]=cp_als.cp_als(X1,r)
# print sol1.totensor().data
# print rX1.data

# Tucker-ALS
[T2, rX2] = tucker_als(X1, R, Omega1)  # if no missing data just omit Omega1
# FalRTC, SiLRTC, HaLRTC
rX3 = falrtc(X1, Omega1)
rX4 = silrtc(X1, Omega1)
rX5 = halrtc(X1, Omega1)
# TNCP
self1 = TNCP(X1, Omega1, rank=r)
self1.run()

# Error Testing
from pyten.tools import tenerror

realX = sol1.totensor()
[Err1, ReErr11, ReErr21] = tenerror(rX1, realX, Omega1)
[Err2, ReErr12, ReErr22] = tenerror(rX2, realX, Omega1)
[Err3, ReErr13, ReErr23] = tenerror(rX3, realX, Omega1)
[Err4, ReErr14, ReErr24] = tenerror(rX4, realX, Omega1)
[Err5, ReErr15, ReErr25] = tenerror(rX5, realX, Omega1)
[Err6, ReErr16, ReErr26] = tenerror(self1.X, realX, Omega1)
print '\n', 'The Relative Error of the Six Methods are:', ReErr21, ReErr22, ReErr23, ReErr24, ReErr25, ReErr26


CP_ALS:

CP_ALS: iterations=100, f-delta=0.0339448408822

Tucker Alternating Least-Squares:

 Tucker_ALS: iterations=100, fit = 0.905352452559, fit-delta = 0.0182081396143

FaLRTC ends: total iterations = 100   difference = [  3.15018662e-05]


SiLRTC ends: total iterations = 41   difference = [  9.15793427e-06]


HaLRTC ends: total iterations = 2   difference = [ 0.]


TNCP: iterations=286, difference=9.91041132245e-06

The Relative Error of the Six Methods are: 0.0300208389496 0.203088424508 0.248158484415 1.0 1.0 0.00412317955676


#### 2. Real Problem - Image Recovery

In [16]:
import matplotlib.image as mpimg  # Use it to load image
import numpy as np

lena = mpimg.imread("testImg.png")
im = np.double(np.uint8(lena * 255))
im = im[0:50, 0:50, 0:3]

from pyten.tenclass import Tensor  # Use it to construct Tensor object

X1 = Tensor(im)   # Construct Image Tensor to be Completed
X0 = X1.data.copy()
X0 = Tensor(X0)   # Save the Ground Truth
Omega1 = (im < 100) * 1.0  # Missing index Tensor
X1.data[Omega1 == 0] = 0


# Basic Tensor Completion with methods: CP-ALS, Tucker-ALS, FaLRTC, SiLRTC, HaLRTC, TNCP
from pyten.method import *

r = 10
R = [10, 10, 3]  # Rank for tucker-based methods
[T1, rX1] = cp_als(X1, r, Omega1, maxiter=100, printitn=100)
[T2, rX2] = tucker_als(X1, R, Omega1, maxiter=100, printitn=100)
alpha = np.array([1.0, 1.0, 1e-3])
alpha = alpha / sum(alpha)
rX3 = falrtc(X1, Omega1, maxIter=100, alpha=alpha)
rX4 = silrtc(X1, Omega1, maxIter=100, alpha=alpha)
rX5 = halrtc(X1, Omega1, maxIter=100, alpha=alpha)
self1 = TNCP(X1, Omega1, rank=r)
self1.run()

# Error Testing
from pyten.tools import tenerror

realX = X0
[Err1, ReErr11, ReErr21] = tenerror(rX1, realX, Omega1)
[Err2, ReErr12, ReErr22] = tenerror(rX2, realX, Omega1)
[Err3, ReErr13, ReErr23] = tenerror(rX3, realX, Omega1)
[Err4, ReErr14, ReErr24] = tenerror(rX4, realX, Omega1)
[Err5, ReErr15, ReErr25] = tenerror(rX5, realX, Omega1)
[Err6, ReErr16, ReErr26] = tenerror(self1.X, realX, Omega1)
print '\n', 'The Relative Error of the Six Methods are:', ReErr21, ReErr22, ReErr23, ReErr24, ReErr25, ReErr26



CP_ALS:

CP_ALS: iterations=100, f-delta=6.69287507888

Tucker Alternating Least-Squares:

 Tucker_ALS: iterations=100, fit = 0.469672142569, fit-delta = 0.170164637317

FaLRTC ends: total iterations = 100   difference = [ 0.0003211]


SiLRTC ends: total iterations = 100   difference = [ 0.00051051]


HaLRTC ends: total iterations = 20   difference = [  3.65196896e-06]


TNCP: iterations=486, difference=9.64393311028e-06

The Relative Error of the Six Methods are: 0.937377236795 1.04476470657 0.756331723593 0.999998266198 0.999998266198 0.92370940921


### Scenario 2: Tensor Completion/Decomposition with Auxiliary Information
#### 1. Use  AirCP Method to solve Tensor Completion With Auxiliary Similarity Matrices

In [17]:
from pyten.method import AirCP  # Import AirCP
from pyten.tools import create  # Import the problem creation function

problem = 'auxiliary'  # Define Problem As Basic Tensor Completion Problem
siz = [20, 20, 20]  # Size of the Created Synthetic Tensor
r = [4, 4, 4]  # Rank of the Created Synthetic Tensor
miss = 0.8  # Missing Percentage
tp = 'sim'  # Define Auxiliary Information As 'Similarity Matrices'
# Construct Similarity Matrices (if 'None', then it will use the default Similarity Matrices)
# aux = [np.diag(np.ones(siz[n]-1), -1)+np.diag(np.ones(siz[n]-1), 1) for n in range(dims)]
aux = None
[X1, Omega1, sol1, sim_matrices] = create(problem, siz, r, miss, tp, aux=aux)

self = AirCP(X1, Omega1, r, simMats=sim_matrices)
self.run()
self_no_aux = AirCP(X1, Omega1, r)
self_no_aux.run()

# Error Testing
from pyten.tools import tenerror

realX = sol1.totensor()
[Err1, ReErr11, ReErr21] = tenerror(self.X, realX, Omega1)
[Err2, ReErr12, ReErr22] = tenerror(self_no_aux.X, realX, Omega1)
print '\n','The Relative Error of the Two Methods are:', ReErr11, ReErr12


AirCP: iterations=405, difference=9.71552958233e-06
AirCP: iterations=419, difference=9.98775316422e-06

The Relative Error of the Two Methods are: 0.0449095484235 0.0498219465437


#### 2. Use  CMTF Method to solve Tensor Completion With Coupled Matrices

In [18]:
from pyten.method import cmtf
from pyten.tools import create  # Import the problem creation function
import numpy as np

problem = 'auxiliary'  # Define Problem As Basic Tensor Completion Problem
siz = [20, 20, 20]  # Size of the Created Synthetic Tensor
r = [4, 4, 4]  # Rank of the Created Synthetic Tensor
miss = 0.8  # Missing Percentage
tp = 'couple'  # Define Auxiliary Information As 'Similarity Matrices'
# Construct Similarity Matrices (if 'None', then it will use the default Similarity Matrices)
dims = 3
[X1, Omega1, sol1, coupled_matrices] = create(problem, siz, r, miss, tp)

[T1, Rec1, V1] = cmtf(X1, coupled_matrices, [1, 2, 3], r, Omega1, maxiter=500)
[T2, Rec2, V2] = cmtf(X1, None, None, r, Omega1, maxiter=500)
fit_coupled_matrices_1 = [np.dot(T1.Us[n], V1[n].T) for n in range(dims)]

# Error Testing
from pyten.tools import tenerror

realX = sol1.totensor()
[Err1, ReErr11, ReErr21] = tenerror(Rec1, realX, Omega1)
[Err1, ReErr12, ReErr22] = tenerror(Rec2, realX, Omega1)
print '\n','The Relative Error of the Two Methods are:', ReErr11, ReErr12


CMTF:

CMTF: iterations=100, f-delta=1.8816390529
CMTF: iterations=200, f-delta=0.594719871935
CMTF: iterations=300, f-delta=0.302207645634
CMTF: iterations=400, f-delta=0.379488775109
CMTF: iterations=500, f-delta=0.909666426043

CP_ALS:

CP_ALS: iterations=100, f-delta=0.0146474854183
CP_ALS: iterations=200, f-delta=0.00203955632878
CP_ALS: iterations=300, f-delta=0.00118894804588
CP_ALS: iterations=400, f-delta=0.000790724804106
CP_ALS: iterations=500, f-delta=0.000551860811849

The Relative Error of the Two Methods are: 0.111786036229 0.0029689406707


### Scenario 3: Dynamic Tensor Decomposition/Completion

In [19]:
from pyten.method import onlineCP, OLSGD
from pyten.tools import create  # Import the problem creation function
from pyten.tools import tenerror
import numpy as np

problem = 'dynamic'  # Define Problem As Dynamic Tensor Completion Problem
time_steps = 10  # Define the Number of Total Time Steps
siz = np.array([[1, 50, 50] for t in range(time_steps)])
r = [4, 4, 4]  # Rank of the Created Synthetic Tensor
miss = 0.8  # Missing Percentage
# Create a Dynmaic Tensor Completion Problem
[X1, Omega1, sol1, siz, time_steps] = create(problem, siz, r, miss, timestep=time_steps)

for t in range(time_steps):
    if t == 0:  # Initial Step
        self1 = OLSGD(rank=r, mu=0.01, lmbda=0.1)  # OLSGD assume time is the first mode.
        self1.update(X1[t], Omega1[t])  # Complete the initial tensor using OLSGD method.
        # onlineCP assume time is the last mode.
        self = onlineCP(X1[t].permute([1, 2, 0]), rank=r, tol=1e-8)  # Just decompose without completion using onlineCP
    else:
        self1.update(X1[t], Omega1[t])  # Update Decomposition as well as Completion using OLSGD.
        self.update(X1[t].permute([1, 2, 0]))  # Update Decomposition of onlineCP.
    # Test Current Step OLSGD Completion Error
    realX = sol1[t].totensor()
    [Err1, ReErr11, ReErr21] = tenerror(self1.recx, realX, Omega1[t])
    print Err1, ReErr11, ReErr21


CP_ALS:

CP_ALS: iterations=100, f=0.247022222543, f-delta=3.07595118155e-05
168483.054778 6273.93136731 6956.77678839
39.3607170086 1.92478774564 2.16851751468
23.8776902888 0.967379097904 1.06981125749
28.4928290082 0.895845446384 1.00324310955
24.6956914088 0.887524791567 1.0009380212
25.882510805 0.897823327078 1.00423099729
12.6966740493 0.893965752495 1.00014620856
32.8171867268 0.894934521631 0.999920117901
36.4418243405 0.894945725459 0.99991406763
34.8890398511 0.932485252995 1.04681679048
